In [2]:
import numpy as np

In [3]:
lista = [1,2,3,4,5,6,7,8,9]
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
arr = np.array(lista)

In [5]:
type(arr)

numpy.ndarray

In [6]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
matriz = [[1,2,3],[4,5,6],[7,8,9]]
matriz = np.array(matriz)
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
arr[0]

1

In [10]:
arr[0] + arr[5]

7

In [11]:
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
matriz[0, 2]

3

In [13]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
arr[1:6]

array([2, 3, 4, 5, 6])

In [20]:
arr[2:]

array([3, 4, 5, 6, 7, 8, 9])

In [23]:
arr[::3]

array([1, 4, 7])

In [25]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
arr[-3:]

array([7, 8, 9])

In [30]:
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
matriz[1:,0:2]

array([[4, 5],
       [7, 8]])

In [60]:
matriz_de_cuatro = [[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]]

matriz_de_cuatro = np.array(matriz_de_cuatro)

matriz_de_cuatro

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [62]:
matriz_de_cuatro[0:,2:3]

array([[ 3],
       [ 7],
       [11],
       [15]])