In [1]:
import numpy as np

In [2]:
# Array int por default

arr = np.arange(5)
arr.dtype

dtype('int64')

In [3]:
# Array de tipo float

arr = np.arange(5, dtype='float64')
arr.dtype

dtype('float64')

In [4]:
arr

array([0., 1., 2., 3., 4.])

In [5]:
arr = arr.astype(np.float64)

In [6]:
arr.dtype

dtype('float64')

In [7]:
# Array de tipo booleano

arr = np.arange(5)
arr = arr.astype(np.bool_)
arr

array([False,  True,  True,  True,  True])

In [8]:
# Array de tipo string

arr = np.arange(5)
arr = arr.astype(np.string_)
arr

array([b'0', b'1', b'2', b'3', b'4'], dtype='|S21')

In [9]:
# Convirtiendo array de tipo String a Int

arr = np.array(['0', '1', '2', '3', '4'])
arr = arr.astype(np.int8)
arr

array([0, 1, 2, 3, 4], dtype=int8)

In [14]:
arr

array([0, 1, 2, 3, 4], dtype=int8)